# Generated by Django 2.1.7 on 2019-04-11 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch_pr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=20, unique=True)),
                ('b_year', models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=1)),
                ('b_month', models.CharField(blank=True, editable=False, max_length=1)),
                ('b_number', models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=4)),
            ],
            options={
                'ordering': ['b_year', 'b_month', 'b_number'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(max_length=20, unique=True)),
                ('prod_lot', models.CharField(max_length=30)),
                ('expire', models.DateField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Production2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_decl_quantity', models.DecimalField(decimal_places=3, max_digits=7)),
                ('prod_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docview.Batch_pr')),
            ],
        ),
        migrations.CreateModel(
            name='Raw_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('material_name', models.CharField(max_length=120, unique=True)),
                ('unit', models.CharField(default='кг', max_length=3)),
                ('rate', models.IntegerField(default=1)),
                ('barcode', models.CharField(blank=True, max_length=13, null=True, unique=True)),
            ],
            options={
                'ordering': ['material_name'],
            },
        ),
        migrations.CreateModel(
            name='Row_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.CharField(max_length=20, unique=True)),
                ('r_date', models.DateField(blank=True, editable=False)),
                ('r_time', models.TimeField(blank=True, editable=False)),
                ('r_device', models.CharField(blank=True, editable=False, max_length=3)),
            ],
            options={
                'ordering': ['r_id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='W_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_user_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=7)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docview.Batch_pr')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docview.Lot')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docview.Raw_material')),
                ('w_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docview.W_user')),
                ('weighting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docview.Row_id')),
            ],
            options={
                'ordering': ['batch', 'material'],
            },
        ),
        migrations.AddField(
            model_name='production2',
            name='prod_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docview.Raw_material'),
        ),
        migrations.AddField(
            model_name='lot',
            name='producer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docview.Producer'),
        ),
        migrations.AddField(
            model_name='lot',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docview.Supplier'),
        ),
    ]
