# Generated by Django 2.1.7 on 2019-04-05 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch_pr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raw_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('material_name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Row_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['r_id'],
            },
        ),
        migrations.CreateModel(
            name='Weighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=7)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docview.Batch_pr')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docview.Lot')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docview.Raw_material')),
                ('w_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weighting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docview.Row_id')),
            ],
        ),
    ]
