# Generated by Django 2.1.7 on 2019-04-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='W_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_user_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='weighting',
            name='w_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docview.W_user'),
        ),
    ]
