# Generated by Django 2.1.7 on 2019-04-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch_pr',
            options={},
        ),
        migrations.RemoveField(
            model_name='batch_pr',
            name='b_month',
        ),
        migrations.RemoveField(
            model_name='batch_pr',
            name='b_number',
        ),
        migrations.RemoveField(
            model_name='batch_pr',
            name='b_year',
        ),
    ]
