# Generated by Django 2.1.7 on 2019-04-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docview', '0002_auto_20190405_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch_pr',
            options={'ordering': ['batch_name']},
        ),
        migrations.AlterModelOptions(
            name='raw_material',
            options={'ordering': ['material_name']},
        ),
        migrations.AlterModelOptions(
            name='weighting',
            options={'ordering': ['batch', 'material']},
        ),
        migrations.AddField(
            model_name='batch_pr',
            name='b_month',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='batch_pr',
            name='b_number',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='batch_pr',
            name='b_year',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
