# Generated by Django 2.1.7 on 2019-04-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docview', '0003_auto_20190406_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch_pr',
            options={'ordering': ['b_year', 'b_month', 'b_number']},
        ),
        migrations.AlterField(
            model_name='batch_pr',
            name='b_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='batch_pr',
            name='b_year',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1),
        ),
    ]
