# Generated by Django 2.1.7 on 2019-04-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docview', '0005_auto_20190406_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch_pr',
            name='b_year',
            field=models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=1),
        ),
    ]
