# Generated by Django 2.1.7 on 2019-04-06 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docview', '0006_auto_20190406_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='row_id',
            name='r_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='row_id',
            name='r_device',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='row_id',
            name='r_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch_pr',
            name='b_month',
            field=models.CharField(blank=True, editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='batch_pr',
            name='b_number',
            field=models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=4),
        ),
    ]
