# Generated by Django 2.1.7 on 2019-04-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docview', '0007_auto_20190406_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_material',
            name='barcode',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='raw_material',
            name='rate',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='raw_material',
            name='unit',
            field=models.CharField(default='кг', max_length=3),
        ),
    ]
