# Generated by Django 2.1.7 on 2019-04-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docview', '0010_auto_20190411_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_material',
            name='material_name',
            field=models.CharField(max_length=120),
        ),
    ]
